import Charts
import SwiftUI

public struct ForecastView: View {
    @ObservedObject private var model: AppModel
    @Binding private var symbol: String
    public init(model: AppModel, symbol: Binding<String>) { self.model = model; _symbol = symbol }
    public var body: some View {
        Group { if model.featureLoading && model.forecast == nil { ProgressView("Loading forecast…") } else if let error = model.forecastError, model.forecast == nil { DashboardCard { VStack(alignment: .leading, spacing: 8) { Label("Forecast unavailable", systemImage: "exclamationmark.triangle.fill").foregroundStyle(DashboardTheme.risk); Text(error).font(.caption).foregroundStyle(.white) } } } else if let data = model.forecast { content(data) } }.task(id: symbol) { await model.loadForecast(symbol: symbol) }
    }
    private func content(_ data: ForecastResponse) -> some View { ScrollView { VStack(alignment: .leading, spacing: 16) { HStack(alignment: .bottom) { VStack(alignment: .leading, spacing: 7) { Text("FORECAST / SELECTED ASSET").font(.caption.weight(.bold)).tracking(1.8).foregroundStyle(DashboardTheme.primary); Text("Volatility forecast").font(.title2.weight(.bold)); Text("Near-term model estimates for \(data.symbol).").foregroundStyle(DashboardTheme.muted) }; Spacer(); Label(data.freshness.forecastStatus, systemImage: "clock.fill").font(.caption).foregroundStyle(data.freshness.isCurrent ? DashboardTheme.positive : DashboardTheme.risk) }; HStack { meta("Trained through", date(data.freshness.modelTrainingCutoff)); meta("Forecast window", "\(date(data.freshness.forecastStartDate)) – \(date(data.freshness.forecastEndDate))") }.fixedSize(horizontal: false, vertical: true); DashboardCard { VStack(alignment: .leading, spacing: 5) { Text("Forecasted volatility • \(data.symbol)").font(.headline.weight(.bold)); Text("Daily volatility in percentage points").font(.caption).foregroundStyle(DashboardTheme.muted); Chart { ForEach(data.forecasts) { item in LineMark(x: .value("Date", item.forecastDate), y: .value("Volatility", item.volatilityPct)).foregroundStyle(DashboardTheme.risk).symbol(.circle) } }.chartYAxis { AxisMarks { AxisGridLine().foregroundStyle(DashboardTheme.border); AxisValueLabel().foregroundStyle(DashboardTheme.muted) } }.frame(height: 280) } }; DashboardCard { VStack(alignment: .leading, spacing: 10) { Text("What this means").font(.headline.weight(.bold)); Text("The model estimates volatility over the next \(data.horizon) trading sessions. This output is labeled \(data.freshness.forecastStatus) because the available price data is not current.").foregroundStyle(.white).fixedSize(horizontal: false, vertical: true); Text("Forecasts are probabilistic and educational, not investment advice.").font(.caption).foregroundStyle(DashboardTheme.muted) } } }.padding(24) } }
    private func meta(_ label: String, _ value: String) -> some View { Text("\(label): \(value)").font(.caption).foregroundStyle(DashboardTheme.muted).padding(10).background(DashboardTheme.panelRaised).clipShape(RoundedRectangle(cornerRadius: 8)) }
    private func date(_ value: Date) -> String { value.formatted(date: .abbreviated, time: .omitted) }
}
